spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/blog_engine}
    username: ${U_NAME}
    password: ${U_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true

spring.jpa.show-sql: true
properties.hibernate.dialect: org.hibernate.dialect.MySQL7Dialect
enable_lazy_load_no_trans: true
logging.level.org.springframework: info



#data init
blog.title: DevPub
blog.subtitle: Интересные истории
blog.phone: +7-913-450-68-60
blog.email: iGarik10@yandex.ru
blog.copyright: Oleg Prokhorov
blog.copyrightFrom: 2021
#lifetime in seconds
blog.lifeTimeCaptchaCode: 1800
#password all users 12345678
#mail data

blog:
  myPassword: ${EMAIL_PSW}
  myEmail: ${EMAIL_BG}
  address: https://oleg-pr-skillbox.herokuapp.com/login/change-password/
#Cloudinary
blog.cloud_name: ${CLOUD_NAME}
blog.api_key: ${CLOUD_KEY}
blog.api_secret: ${CLOUD_SECR}

server:
  port: ${PORT:8080}